---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 756952110860759041-17Z0NodvhyKiWxma8RCBIMMbkR022pY
:access_token_secret: TqiucZONsNgndsZNNVcRWGqTi0MJON83QfXY3rSZ6Ht0W
